name: Build APK

on:
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - run: sudo apt-get update && sudo apt-get install -y unzip

  - run: unzip "LeviLaunchroid-1.4.10-32bit-source.zip" -d source

  - uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: '17'

  - name: Show extracted files
    run: find source

  - name: Upload source listing
    uses: actions/upload-artifact@v4
    with:
      name: source-tree
      path: source
